name: Init Project
on:
  workflow_dispatch:
    inputs:
      challengeRef:
        description: 'Github reference for the challenge to be copied'
        required: true
        default: 'refs/heads/challenge-1'
      reviewers:
        description: Github username of the person who should be auto-assigned to the candidate's PR
        required: false
        default: ''
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  CHALLENGE_REF: '${{ github.event.inputs.challengeRef }}'
  DEFAULT_REVIEWERS: '${{ github.event.inputs.reviewers }}'
jobs:
  build:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Checkout challenge branch
        uses: actions/checkout@v3
        with:
          repository: REDspace-recruiting/react-pokedex
          ref: ${{ env.CHALLENGE_REF }}
          token: ${{ env.GH_TOKEN }}
          path: './pokedex'
      - name: Move files into root (rsync)
        run: rsync -av --progress ./pokedex/ ./ --exclude .git --exclude .github
      - name: Remove old directory
        run: rm -rf ./pokedex
      - name: Add the default reviewers
        run: printf '${{ env.DEFAULT_REVIEWERS }}' | tr ',' '\n' | xargs -I reviewer echo - reviewer >> ./.github/auto_assign.yml
      - name: Commit
        run: |
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --local user.name github-actions[bot]ername@users.noreply.github.com
          git add --all
          git commit -m "Include challenge files"
          git push
      